[package]
name = "libpulse-mainloop-glib-sys"
version = "1.3.4"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
description = """
A Rust language linking library for the PulseAudio libpulse-mainloop-glib library.
"""
keywords = ["binding", "pulse", "pulseaudio", "pulse-mainloop-glib", "audio"]
links = "pulse-mainloop-glib"
build = "build.rs"
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"

[dependencies]
libpulse-sys = { path = "../pulse-sys", version = "1.3", default-features = false }

[target.'cfg(target_os="linux")'.build-dependencies]
pkg-config = "0.3"

[features]
default = ["pa_encoding_from_string"]
#include format::Encoding::from_string method, for which the underlying C API symbol was missing before PA v12
pa_encoding_from_string = ["libpulse-sys/pa_encoding_from_string"]

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
