[package]
name = "libpulse-sys"
version = "1.3.4"
authors = ["Lyndon Brown <jnqnfe@gmail.com>"]
license = "LGPL-2.1+"
description = """
A Rust language linking library for the PulseAudio libpulse library.
"""
keywords = ["sys", "binding", "pulse", "pulseaudio", "audio"]
links = "pulse"
build = "build.rs"
homepage = "https://github.com/jnqnfe/pulse-binding-rust"
repository = "https://github.com/jnqnfe/pulse-binding-rust"

[dependencies]
libc = "0.2"

[target.'cfg(target_os="linux")'.build-dependencies]
pkg-config = "0.3"

[features]
default = ["pa_encoding_from_string"]
#include pa_encoding_from_string function, symbol for which might be missing before PA v12
pa_encoding_from_string = []

[badges]
travis-ci = { repository = "jnqnfe/pulse-binding-rust" }
